name: flutter_iconoir_ttf
description: 'The free open source Iconoir icons for Flutter without dependency on flutter_svg as they are font based. You can just use the standard Icon widget!'
version: 0.0.9
repository: 'https://github.com/aakhil-kassim/flutter_iconoir_ttf'


environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: IconoirIconsRegular
      fonts:
        - asset: fonts/IconoirIconsRegular.ttf
    - family: IconoirIconsBold
      fonts:
        - asset: fonts/IconoirIconsBold.ttf