name: flutter_iconoir_ttf
description: 'The free open source Iconoir icons for Flutter without dependency on flutter_svg. You cna just use the standard Icon widget!'
version: 0.0.7
repository: 'https://github.com/aakhil-kassim/flutter_iconoir_ttf'


environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: IconoirIcons
      fonts:
        - asset: fonts/iconoir_icons_regular.ttf
          weight: 500
        - asset: fonts/iconoir_icons_bold.ttf
          weight: 700
    - family: IconoirIconsBold
      fonts:
        - asset: fonts/iconoir_icons_bold.ttf